yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView, name='author'),
    path('tech/', views.AboutTechView, name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/create/', views.group_create, name='group_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('group/<slug:slug>/delete', views.group_delete, name='group_delete'),
    path('group/<slug:slug>/edit', views.group_edit, name='group_edit'),
    path('groups/', views.groups, name='groups'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/delete', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Описание группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Короткий адрес группы',
        help_text='Короткий адрес группы'
    )
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Название группы'
    )

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    author = models.ForeignKey(
        User,
        help_text='Автор поста',
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        help_text='Группа, к которой будет относиться пост',
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        blank=True,
        upload_to='posts/',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='Дата публикации поста',
        verbose_name='Дата публикации поста',
    )
    text = models.TextField(
        help_text='Введите текст поста',
        verbose_name='Текст поста',
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    created = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='Дата публикации комментария',
        verbose_name='Дата публикации комментария',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        help_text='Введите текст комментария',
        verbose_name='Текст комментария',
    )


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Group, Post


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = (
            'text',
        )


class GroupForm(forms.ModelForm):
    class Meta():
        model = Group
        fields = (
            'title',
            'description',
            'slug',
        )


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )
        help_texts = {
            "group": {
                "edit": "Группа, к которой относится пост",
                "new": "Группа, к которой будет относиться пост",
            },
            "text": {
                "edit": "Текст поста",
                "new": "Текст нового поста",
            },
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from yatube.settings import CACHE_TIME

from .forms import CommentForm, GroupForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator

SHOW_COUNT: int = 10


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = paginator(posts, SHOW_COUNT, request)
    context = {
        'page_obj': page_obj,
        'index_header': True
    }
    return render(request, 'posts/follow.html', context)


@login_required
def group_create(request):
    form = GroupForm(
        request.POST or None,
    )
    context = {
        'form': form,
        'group_create': True
    }
    if not form.is_valid():
        return render(request, 'posts/create_group.html', context)
    group = form.save(commit=False)
    group.author = request.user
    group.save()
    return redirect('posts:groups')


@login_required
def group_edit(request, slug):
    group = get_object_or_404(Group, slug=slug)
    form = GroupForm(
        request.POST or None,
        instance=group,
    )
    context = {
        'form': form,
        'is_edit': True,
        'group': group,
    }
    if not form.is_valid():
        return render(request, 'posts/create_group.html', context)

    group = form.save(commit=True)
    return redirect('posts:groups')


@login_required
def group_delete(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group.delete()
    return redirect('posts:groups')


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator(posts, SHOW_COUNT, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def groups(request):
    groups = Group.objects.all
    context = {
        'groups': groups,
        'groups_page': True
    }
    return render(request, 'posts/groups.html', context)


@cache_page(CACHE_TIME, key_prefix='index_page')
def index(request):
    posts = Post.objects.all()
    page_obj = paginator(posts, SHOW_COUNT, request)
    context = {
        'page_obj': page_obj,
        'index_header': True,
        'index': True
    }
    return render(request, 'posts/index.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {
        'form': form,
        'post_create': True
    }
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author.username == request.user.username:
        post.delete()
    return redirect('posts:profile', request.user.username)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all().order_by('created')
    count = post.author.posts.count()
    form = CommentForm(
        request.POST or None
    )
    context = {
        'comments': comments,
        'count': count,
        'form': form,
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:profile', request.user.username)

    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None
    )
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)

    post = form.save(commit=True)
    return redirect('posts:post_detail', post.id)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator(posts, SHOW_COUNT, request)
    count = posts.count()
    following = author.following.filter(user=request.user.id).exists()
    context = {
        'author': author,
        'count': count,
        'following': following,
        'page_obj': page_obj,
        'profile': True
    }
    return render(request, 'posts/profile.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.follower.filter(author=author).exists()
    if request.user != author and not following:
        follow = Follow(user=request.user, author=author)
        follow.save()
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow = Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    )
    follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_group.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}

{% block header %}
  Сохранить 
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            Сохранить               
          </div>
          <div class="card-body">
            <form method="post"enctype="multipart/form-data"> 
              {% csrf_token %} 
              {% for field in form %} 

                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}             
                      <span class="required text-danger" >*</span>   
                    {% endif %}               
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}      
                    <small id="{{ field.id_for_label }}" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>      
                  {% endif %} 
              
                </div>            
              {% endfor %}
              {% for error in form.errors %}
              <p>Некорректный {{ error }}</p>
              {% endfor %}  

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-primary">
                  Сохранить            
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}

{% block header %}
  {% if is_edit %}
    Редактировать
  {% else %}
    Сохранить
  {% endif %}    
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать
            {% else %}
              Сохранить
            {% endif %}                  
          </div>
          <div class="card-body">
            <form method="post"enctype="multipart/form-data"> 
              {% csrf_token %} 
              {% for field in form %}    
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}             
                      <span class="required text-danger" >*</span>   
                    {% endif %}               
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}      
                    <small id="{{ field.id_for_label }}" class="form-text text-muted">
                      {% if is_edit %}
                        {{ field.help_text.edit|safe }}  
                      {% else %}
                        {{ field.help_text.new|safe }}
                      {% endif %}
                    </small>      
                  {% endif %}            
                </div>            
              {% endfor %}
              {% for error in form.errors %}
                <p>Некорректный {{ error }}</p>
              {% endfor %}  
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}               
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}   

{% block header %}
  Ваши подписки
{% endblock %}

{% block content %}
  <div class="container py-5">     
    <h1>Ваши подписки</h1>
    {% include 'posts/includes/switcher.html' with follow=True index_header=True %}
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: 
              {% if post.author.get_full_name %}
                <a href="{% url 'posts:profile' post.author.username %}">
                  {{ post.author.get_full_name }}
                </a>
              {% else %}
                <a href="{% url 'posts:profile' post.author.username %}">
                  {{ post.author.username }}
                </a>
              {% endif%}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li>
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
            </li>
            {% endif %} 
          </ul>
          <p>{{ post.text }}</p>
          {% thumbnail post.image "1440x560" crop="center" upscale=False as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %} 
          <button 
            class="btn btn-outline-primary" 
            onclick="window.location.href = '{% url 'posts:post_detail' post.id %}'"
            type="button"
          >
            Подробная информация 
          </button>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}   

{% block header %}
  {{ group.title }}
{% endblock %}

{% block content %}
  <div class="container py-5">     
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: 
            {% if post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
              </a>
            {% else %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.username }}
              </a>
            {% endif%}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        {% thumbnail post.image "1440x560" crop="center" upscale=False as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        <button 
          class="btn btn-outline-primary" 
          onclick="window.location.href = '{% url 'posts:post_detail' post.id %}'"
          type="button"
        >
          Подробная информация 
        </button>
        {% if post.author.username == request.user.username %}
          <button 
            class="btn btn-outline-danger" 
            onclick="window.location.href = '{% url 'posts:post_delete' post.id %}'"
            type="button"
          >
            Удалить пост
          </button>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/groups.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
  Группы
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Группы</h1>
      <article>
        <p></p>
        {% for group in groups %}
          <h5>Группа: {{ group.title }}</h5>
          <p>{{ group.description }}</p>
          <p>
            <a class="btn btn-outline-primary" href="{% url 'posts:group_list' group.slug %}">Записи группы</a>
            <a class="btn btn-outline-primary" href="{% url 'posts:group_edit' group.slug %}">Редактировать группу</a>
            <a class="btn btn-outline-danger" href="{% url 'posts:group_delete' group.slug %}">Удалить группу</a>
          </p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %} 
{% load thumbnail %}
{% load static %}
{% block header %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' with index_header=True index=True %}
      {% cache 20 index_page page_obj.number %} 
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: 
                {% if post.author.get_full_name %}
                  <a href="{% url 'posts:profile' post.author.username %}">
                    {{ post.author.get_full_name }}
                  </a>
                {% else %}
                  <a href="{% url 'posts:profile' post.author.username %}">
                    {{ post.author.username }}
                  </a>
                {% endif%}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
              {% if post.group %}
              <li>
                Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
              </li>
              {% endif %} 
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "1440x560" crop="center" upscale=False as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %} 
            <button 
              class="btn btn-outline-primary" 
              onclick="window.location.href = '{% url 'posts:post_detail' post.id %}'"
              type="button"
            >
              Подробная информация 
            </button>
            {% if post.author.username == request.user.username %}
              <button 
                class="btn btn-outline-danger" 
                onclick="window.location.href = '{% url 'posts:post_delete' post.id %}'"
                type="button"
              >
                Удалить пост
              </button>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
      {% endcache %}  
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}   

{% block header %}
  Пост {{ post.text|truncatechars:30}}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
            </li>
            {% endif %} 
          <li class="list-group-item">
            Автор:
            {% if post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
              </a>
            {% else %}
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.username }}
              </a>
            {% endif%}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ count }}</span>
          </li>
          {% if post.author == request.user %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <a class="btn btn-outline-danger" href="{% url 'posts:post_delete' post.id %}">
                Удалить пост
              </a>
            </li>
          {% endif%}
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "1440x560" crop="center" upscale=False as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if post.author == request.user %}
          <a class="btn btn-outline-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
        {% include 'includes/comments.html' %} 
      </article>
    </div> 
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block header %}
  Профайл пользователя {{ author.username }}
{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="mb-5">      
      <h1>Все посты пользователя
        {% if not author.get_full_name %}
          {{ author.username }}
        {% endif%}
        {{ author.get_full_name }} 
      </h1>
      <h3>Всего постов: {{ count }}</h3>
      {% if request.user.username != author.username %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
          {% if post.group %}
          <li>
            Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
          </li>
          {% endif %} 
        </ul>
        <p>{{ post.text }}</p>
        {% thumbnail post.image "1440x560" crop="center" upscale=False as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        <button 
          class="btn btn-outline-primary" 
          onclick="window.location.href = '{% url 'posts:post_detail' post.id %}'"
          type="button"
        >
          Подробная информация 
        </button>
        {% if post.author.username == request.user.username %}
          <button 
            class="btn btn-outline-danger" 
            onclick="window.location.href = '{% url 'posts:post_delete' post.id %}'"
            type="button"
          >
            Удалить пост
          </button>
         {% endif %}
        {% if not forloop.last %}<hr>{% endif %}       
      {% endfor %} 
    </article> 
    {% include 'posts/includes/paginator.html' %}   
  </div>
{% endblock %}